on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Run tests
        run: go test -v ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
